version: '3.8'

services:
 
  api:
    build: .
    container_name: restaurant_api
    ports:
      - "8000:8000" 
    depends_on:
      - db  
    environment:
      - DATABASE_URL=postgresql://restaurant_user:PythonProject@db:5432/restaurant_db

    volumes:
      - ./app:/app/app

  
  db:
    image: postgres:15-alpine
    container_name: restaurant_db
    environment:
      POSTGRES_USER: restaurant_user
      POSTGRES_PASSWORD: PythonProject
      POSTGRES_DB: restaurant_db
   
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: