name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: restaurant_user
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: restaurant_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U restaurant_user -d restaurant_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Wait for Postgres
        run: |
          # Shty testet deri sa DB të jetë ready
          until pg_isready -h localhost -p 5432 -U restaurant_user; do
            echo "Waiting for Postgres..."
            sleep 2
          done

      - name: Run tests
        env:
          DATABASE_URL: postgresql://restaurant_user:1234@localhost:5432/restaurant_db
        run: |
          source venv/bin/activate
          pytest -v --tb=short

      - name: Build Docker image
        run: docker build -t restaurant_api:latest .

      - name: Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: yourdockerhubusername/restaurant_api:latest
